### ISSUE TITLE
Confusion over `skip-compilation` option

### ISSUE THREAD

**Issue by jgfoster** [Arduino-CI/arduino_ci#175]
As described in `REFERENCE.md`, this framework will (_compile_ and) run all the code in the `test` directory on the developer's desktop/laptop against the _mock_ Arduino board. Then, as a separate task an attempt is made to build everything in the `examples` directory using the Arduino IDE (which has different includes and a different compiler) so as to avoid later surprises due to the different build environment and target. These tasks are very reasonable and distinct, but I was confused by the names.

I spent a lot of time fiddling with test code to get the unit tests to _compile_ and run and the idea that I'm running the unit tests without compiling seems very odd. Now that I'm understanding better I wonder if "compilation of examples" would be a better phrase (even though it is more verbose). 

So, the command line option `--skip-compilation` would probably remain but would be deprecated in favor of `--skip-compilation-of-examples` or simply `--skip-examples` (more analogous to `--skip-unittests`).

**Comment by ianfixes** [comment]
I'll probably do `--skip-examples-compilation`, this is a great suggestion
