### ISSUE TITLE
Fix _SFR_IO8 macro to avoid "cannot take the address of an rvalue"

### ISSUE THREAD

**Issue by ianfixes** [Arduino-CI/arduino_ci#187]
## Issue Summary 

see https://github.com/Arduino-CI/SD/issues/2

```
error: cannot take the address of an rvalue of type 'int'
  {&DDRE, &PINE, &PORTE, 0},  // E0  0
   ^~~~~
```

[Working theory](https://github.com/Arduino-CI/SD/issues/2#issuecomment-716266934) is that this is caused by a badly formed macro. 

https://github.com/Arduino-CI/arduino_ci/blob/master/cpp/arduino/avr/io.h#L99

```diff
- #define _SFR_IO8(io_addr) (io_addr) // this macro is all we need from the sfr file 
+ #define _MMIO_BYTE(mem_addr) (*(volatile uint8_t *)(mem_addr))
+ #define _SFR_IO8(io_addr) _MMIO_BYTE((io_addr) + __SFR_OFFSET)
```

Will see if `volatile` is sufficient to fix

**Comment by jgfoster** [comment]
Also see #120. I copied code from there and got things to compile.

**Comment by ianfixes** [comment]
I was able to reproduce this with a unit test, and added the `volatile` keyword (and cast) to fix the error.  Currently in my feature branch.

**Comment by ianfixes** [comment]
This took a lot longer than expected due to chasing my tail on linker errors (and segfaults).  I think I am out of the woods now though.
