### ISSUE TITLE
Add GitHub Actions to enable testing on forks of arduino_ci

### ISSUE THREAD

**Issue by jgfoster** [Arduino-CI/arduino_ci#199]
Set up GitHub Actions for this repository such that forks will have their own functioning CI automatically

Original text:
> `arduino_ci` has two automated testing systems set up. We should add GitHub Actions. (I can work on this but just wanted to note it as an issue.)

**Comment by ianfixes** [comment]
I'm open to this, but I'm not clear on the problem being solved here.  We currently test 3 platforms on every PR or code push: windows, linux, and OSX.  What do GitHub actions add to this?

**Comment by jgfoster** [comment]
This isn't adding a new operating system, this is adding a new testing infrastructure. There are two values: 

First, since `arduino_ci` is a testing framework, it should broadly demonstrate and use the various testing platforms out there. (Actually, I didn't realize that the existing two-part actions were testing three operating systems; I thought that they were demonstrating the two primary testing hosts.)

Second, the two existing testing actions require external setup. While you have gone to the trouble to set up the external systems for this GitHub repository, the rest of us (so far) haven't bothered to do so. The virtue of GitHub Actions is that they are built in to GitHub. By forking your repository I will get the GitHub Action configuration (if/when this PR is accepted). Then my fork will automatically run tests on every push _to my repository._ With that, even if I fail to run the test suite before doing a local commit (hand slap!), one will be run when I do a push. This is pushing best practices to the edge.

**Comment by ianfixes** [comment]
Understood, I think I made the more relevant comment on #200

**Comment by ianfixes** [comment]
Thought better of it, created #203

**Comment by ianfixes** [comment]
I think this is complete, but we can reopen if I'm misreading it
