### ISSUE TITLE
Add demonstration of using GitHub Actions to execute Arduino CI

### ISSUE THREAD

**Issue by ianfixes** [Arduino-CI/arduino_ci#203]
Set up GitHub Actions for this repository to demonstrate how a user of `arduino_ci` would set it up for themselves

Related to #199 but this concerns how an end user (not a contributor to `arduino_ci` itself) would leverage this tool

**Comment by jgfoster** [comment]
Should we choose a project like [Blink](https://github.com/Arduino-CI/Blink) and make it the "poster child" for how the author of an external library would leverage `arduino_ci`? If so, then this issue would be placed there and the local `README.md` would point to that project? (And, perhaps, now that I know a bit more I should re-record the video describing it!?)

**Comment by ianfixes** [comment]
Yes... this might be a sub-task of #164 ... ditto for #77

**Comment by prestoncarman** [comment]
Following the example in #77 and the README example configs, I set up automated testing for these vendors in the [Blink](https://github.com/Arduino-CI/Blink) repository. The change is in [PR](https://github.com/Arduino-CI/Blink/pull/1). The update includes a table on the README showing all the Vendors and Operating systems that are used in the sample project.

![vendor_os_map](https://user-images.githubusercontent.com/3517157/98850484-b4b50580-2409-11eb-832e-30d9851d61a9.png)

Notes: macOS test is dependent on #199.

**Comment by jgfoster** [comment]
You can get macOS to pass now by explicitly downloading a more recent version of `Arduino.app` in your Action script. See what was [added to Blink](https://github.com/Arduino-CI/Blink/commit/273c26741343f6563030e68f0aee053647841507).

**Comment by ianfixes** [comment]
I really like this, I might not get to it today but I will soon

**Comment by ianfixes** [comment]
I think this is completed, _and_ we have our own action now https://github.com/marketplace/actions/arduino_ci
