### ISSUE TITLE
`ensure_arduino_installation.rb` doesn't create `arduino_library_location.rb`

### ISSUE THREAD

**Issue by jgfoster** [Arduino-CI/arduino_ci#230]
Most of the libraries are working well with `1.0.0` but I've run into a snag on [MAX431865](https://github.com/jgfoster/Adafruit_MAX31865/runs/1477170776?check_suite_focus=true). The problem is I can't install a customer prerequisite library:
```
bundle exec ensure_arduino_installation.rb
cd $(bundle exec arduino_library_location.rb)
ERROR: cd: /home/runner/Arduino/libraries: No such file or directory
```

**Comment by ianfixes** [comment]
Good catch, I will add the `mkdir` operation to `ensure_arduino_installation.rb`
