### ISSUE TITLE
How to print from unit test

### ISSUE THREAD

**Issue by RobTillaart** [Arduino-CI/arduino_ci#243]
How to print from a unit test into its log?
Sometimes I just want to add a comment in the log file.

I might misuse **assertTrue("somstring")**   not tested yet  if that works ...

```cpp
assertNotEqual("", "Hello world, this is a hack");
```  
works :)

**Comment by ianfixes** [comment]
You should be able to just print to STDOUT.  The unit test framework in c++ uses STDERR for all its communication to ensure that nothing is left unreported if there is a segfault.

**Comment by RobTillaart** [comment]
works!
