### ISSUE TITLE
is the random generator in the unit test random?

### ISSUE THREAD

**Issue by RobTillaart** [Arduino-CI/arduino_ci#270]
https://github.com/RobTillaart/weight/runs/1674152502?check_suite_focus=true

specific test_US2metric

it looks like that the random generates only 7 an 2  (call is random(10) )

is this true?

**Comment by ianfixes** [comment]
Short answer: no, on purpose.

The random number generator is here, it just picks a large prime and keeps modding against it:
https://github.com/Arduino-CI/arduino_ci/blob/master/cpp/arduino/Godmode.cpp#L47

It's controlled entirely by the random seed value that you assign it initially, so you can get deterministic test behavior.

**Comment by RobTillaart** [comment]
OK, no problem with it - deterministic is good.
just saw unexpected output to explain by chance alone :)
